markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: daiwk
author: "daiwk"
email: daiwk#foxmail.com
name: "daiwk-github博客"
url: http://daiwk.github.io
domain: daiwk.github.io
all_categories: [
["nlp", "nlp","/posts/nlp.html"], 
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
