markdown: kramdown
highlighter: rouge

permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: daiwk
author: "daiwk"
email: daiwk#foxmail.com
name: "daiwk-github博客"
url: http://daiwk.github.io
domain: daiwk.github.io
all_categories: [
["nlp", "nlp","/posts/nlp.html"], 
["rl", "强化学习","/posts/rl.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["tools", "实用工具", "/posts/tools.html"],
["tools", "deep learning book", "/posts/dlbook.html"],
["about", "关于","/about.html"]
]

paginate: 5
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
 - jekyll-toc


